"use client";

import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Loader2, Search } from "lucide-react";
import { ComplaintDetails, getComplaint } from "@/services/api";
import ComplaintTimeline from "@/components/tracking/ComplaintTimeline";

export default function TrackingClient() {
  const searchParams = useSearchParams();
  const initialComplaintId = searchParams.get("complaintId") ?? "";
  const [complaintId, setComplaintId] = useState(initialComplaintId);
  const [complaint, setComplaint] = useState<ComplaintDetails | null>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  async function track(id: string) {
    if (!id.trim()) return;
    setError("");
    setComplaint(null);
    setIsLoading(true);

    try {
      const details = await getComplaint(id.trim());
      setComplaint(details);
    } catch (trackingError) {
      setError(
        trackingError instanceof Error
          ? trackingError.message
          : "Complaint not found or backend is unavailable."
      );
    } finally {
      setIsLoading(false);
    }
  }

  function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    void track(complaintId);
  }

  useEffect(() => {
    if (initialComplaintId) {
      const lookup = window.setTimeout(() => {
        void track(initialComplaintId);
      }, 0);

      return () => window.clearTimeout(lookup);
    }
  }, [initialComplaintId]);

  return (
    <div className="mx-auto max-w-5xl px-5 py-10 sm:px-8">
      <div className="mb-8">
        <p className="text-sm font-semibold uppercase tracking-wide text-emerald-700">
          Live complaint status
        </p>
        <h1 className="mt-2 text-4xl font-bold text-slate-950">Track your complaint</h1>
        <p className="mt-2 text-slate-600">
          Enter a Delhi Samadhan complaint ID generated by the backend.
        </p>
      </div>

      <form onSubmit={onSubmit} className="mb-6 rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
        <div className="grid gap-3 sm:grid-cols-[1fr_auto]">
          <input
            value={complaintId}
            onChange={(event) => setComplaintId(event.target.value)}
            placeholder="DL-2026-123456"
            className="h-11 rounded-md border border-slate-300 px-3 outline-none focus:border-blue-600"
          />
          <button
            type="submit"
            disabled={isLoading}
            className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-blue-700 px-5 font-semibold text-white hover:bg-blue-800 disabled:bg-blue-300"
          >
            {isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
            Track
          </button>
        </div>
      </form>

      {error && (
        <p className="mb-6 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          {error}
        </p>
      )}

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        <section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-2xl font-semibold text-slate-950">Complaint details</h2>
          {complaint ? (
            <dl className="mt-5 grid gap-4 sm:grid-cols-2">
              {[
                ["ID", complaint.complaintId],
                ["Status", complaint.status],
                ["Category", complaint.category ?? "Pending classification"],
                ["Department", complaint.department ?? "Routing pending"],
                ["Severity", complaint.severity ?? "Pending"],
                ["Last Updated", complaint.lastUpdated ?? "Just now"],
              ].map(([label, value]) => (
                <div key={label} className="rounded-md bg-slate-50 p-4">
                  <dt className="text-sm text-slate-500">{label}</dt>
                  <dd className="mt-1 font-semibold text-slate-950">{value}</dd>
                </div>
              ))}
            </dl>
          ) : (
            <div className="mt-5 rounded-md bg-slate-50 p-5 text-slate-600">
              Tracking results will appear here after a lookup.
            </div>
          )}
        </section>

        <ComplaintTimeline currentStatus={complaint?.status} />
      </div>
    </div>
  );
}
